using System.Security.Cryptography;
using System.Text;
using Mri.Core.Modlist;

namespace Mri.Core.OpenMw;

public sealed record CfgComposition
{
    /// <summary>The vanilla game's "Data Files" directory (absolute).</summary>
    public required string GameDataFilesDir { get; init; }

    /// <summary>Directory all mod DataPaths are relative to (absolute).</summary>
    public required string ModsRootDir { get; init; }

    public required LoadOrderPlan Plan { get; init; }

    /// <summary>fallback= lines harvested from openmw-iniimporter's output.</summary>
    public IReadOnlyList<string> FallbackLines { get; init; } = Array.Empty<string>();

    public bool HasTribunal { get; init; } = true;
    public bool HasBloodmoon { get; init; } = true;

    public string AppVersion { get; init; } = "dev";
    public string ListVersion { get; init; } = "dev";
}

/// <summary>
/// Deterministically generates the complete openmw.cfg. The whole file is
/// owned by the installer (the user's previous cfg is backed up first), so
/// re-running any phase always converges to the same bytes — that's what
/// makes the pipeline steps idempotent and verifiable.
/// </summary>
public static class OpenMwCfgComposer
{
    public const string HeaderPrefix = "# Generated by Morrowind Remake Installer";

    private static readonly string[] VanillaArchives = ["Morrowind.bsa", "Tribunal.bsa", "Bloodmoon.bsa"];

    public static string Compose(CfgComposition c)
    {
        var body = new StringBuilder();

        body.AppendLine("encoding=win1252");

        foreach (var fallback in c.FallbackLines)
            body.AppendLine($"fallback={fallback}");

        body.AppendLine($"fallback-archive={VanillaArchives[0]}");
        if (c.HasTribunal)
            body.AppendLine($"fallback-archive={VanillaArchives[1]}");
        if (c.HasBloodmoon)
            body.AppendLine($"fallback-archive={VanillaArchives[2]}");
        foreach (var archive in c.Plan.FallbackArchives)
            body.AppendLine($"fallback-archive={archive}");

        // Vanilla Data Files first; every later data= dir wins conflicts, so
        // canonical list order IS the overwrite order.
        body.AppendLine($"data={OpenMwCfgWriter.QuotePath(c.GameDataFilesDir)}");
        foreach (var dir in c.Plan.DataDirs)
            body.AppendLine($"data={OpenMwCfgWriter.QuotePath(Path.Combine(c.ModsRootDir, dir))}");

        body.AppendLine("content=Morrowind.esm");
        if (c.HasTribunal)
            body.AppendLine("content=Tribunal.esm");
        if (c.HasBloodmoon)
            body.AppendLine("content=Bloodmoon.esm");
        foreach (var content in c.Plan.ContentFiles)
            body.AppendLine($"content={content}");

        foreach (var groundcover in c.Plan.GroundcoverFiles)
            body.AppendLine($"groundcover={groundcover}");

        var bodyText = body.ToString();
        var header =
            $"{HeaderPrefix} v{c.AppVersion} list {c.ListVersion} hash {HashOf(bodyText)}\n" +
            "# Do not edit below this line — re-running the installer regenerates this file.\n";
        return header + bodyText;
    }

    /// <summary>
    /// True when an existing cfg was produced by <see cref="Compose"/> and its
    /// body still matches its recorded hash — the step verifier's disk truth.
    /// </summary>
    public static bool IsCurrent(string existingText, CfgComposition c) =>
        Normalize(existingText) == Normalize(Compose(c));

    private static string Normalize(string text) =>
        text.Replace("\r\n", "\n").TrimEnd('\n');

    private static string HashOf(string body) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(Normalize(body))))[..12]
            .ToLowerInvariant();
}
