<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>0.1.0</Version>
    <Authors>Brian Honeycutt</Authors>
    <Product>Morrowind Remake Installer</Product>
  </PropertyGroup>
</Project>
