using System.Text;
using Mri.Core.Modlist;

namespace Mri.Curation.Inspect;

/// <summary>
/// Scans the REAL extracted layout of every installed mod and generates
/// dataPaths overrides. Field-motivated: archives nest their content
/// ("Mod_Complete/Data Files/", single wrapper dirs, BAIN "00 Core" variants),
/// and mounting the extract root makes OpenMW silently miss the mod's assets
/// (the pink-texture failure). Unambiguous layouts are auto-fixed; variant
/// choices default to the "00*" core folders with the alternatives listed for
/// curation.
/// </summary>
public static class LayoutInspector
{
    private static readonly HashSet<string> DataDirNames = new(StringComparer.OrdinalIgnoreCase)
    {
        "textures", "meshes", "icons", "fonts", "music", "sound", "sounds", "video",
        "splash", "bookart", "animations", "shaders", "scripts", "l10n", "mwse", "distantland",
    };

    private static readonly HashSet<string> DataFileExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".esp", ".esm", ".omwaddon", ".omwgame", ".omwscripts", ".bsa",
    };

    public sealed record ModInspection(
        string Slug,
        string ExtractTo,
        string Verdict, // ok | auto | core-picked | flagged | missing | no-data
        IReadOnlyList<string> ChosenDataPaths,
        IReadOnlyList<string> OtherCandidates);

    public static bool IsDataRoot(string dir)
    {
        if (!Directory.Exists(dir))
            return false;
        foreach (var entry in Directory.EnumerateFileSystemEntries(dir))
        {
            var name = Path.GetFileName(entry);
            if (Directory.Exists(entry) && DataDirNames.Contains(name))
                return true;
            if (File.Exists(entry) && DataFileExtensions.Contains(Path.GetExtension(name)))
                return true;
        }
        return false;
    }

    /// <summary>All minimal data roots under a mod dir (does not descend below a found root).</summary>
    public static List<string> FindDataRoots(string modDir, int maxDepth = 4)
    {
        var found = new List<string>();

        void Walk(string dir, string rel, int depth)
        {
            if (IsDataRoot(dir))
            {
                found.Add(rel);
                return; // minimal roots only
            }
            if (depth >= maxDepth)
                return;
            foreach (var sub in Directory.EnumerateDirectories(dir).OrderBy(d => d, StringComparer.OrdinalIgnoreCase))
                Walk(sub, rel.Length == 0 ? Path.GetFileName(sub) : $"{rel}/{Path.GetFileName(sub)}", depth + 1);
        }

        if (Directory.Exists(modDir))
            Walk(modDir, "", 0);
        return found;
    }

    public static ModInspection Inspect(string modsRoot, ModEntry mod)
    {
        var extractTo = mod.Downloads.FirstOrDefault()?.ExtractTo ?? mod.Id;
        var modDir = Path.Combine(modsRoot, ModlistCompiler.CategoryDir(mod.Category), extractTo);

        if (!Directory.Exists(modDir))
            return new ModInspection(mod.Id, extractTo, "missing", [], []);

        var roots = FindDataRoots(modDir);
        if (roots.Count == 0)
            return new ModInspection(mod.Id, extractTo, "no-data", [], []);
        if (roots is [""])
            return new ModInspection(mod.Id, extractTo, "ok", [extractTo], []);

        string Rel(string r) => $"{extractTo}/{r}";

        if (roots.Count == 1)
            return new ModInspection(mod.Id, extractTo, "auto", [Rel(roots[0])], []);

        // Prefer an explicit "Data Files" dir when it is unique.
        var dataFiles = roots.Where(r =>
            Path.GetFileName(r).Equals("data files", StringComparison.OrdinalIgnoreCase)).ToList();
        if (dataFiles.Count == 1)
            return new ModInspection(mod.Id, extractTo, "auto", [Rel(dataFiles[0])],
                roots.Except(dataFiles).Select(Rel).ToList());

        // BAIN convention: "00 …" folders are the core; later numbers are options.
        var core = roots.Where(r => Path.GetFileName(r).StartsWith("00", StringComparison.Ordinal))
            .Select(Rel).ToList();
        if (core.Count > 0)
            return new ModInspection(mod.Id, extractTo, "core-picked", core,
                roots.Select(Rel).Except(core).ToList());

        return new ModInspection(mod.Id, extractTo, "flagged", [], roots.Select(Rel).ToList());
    }

    public static (string Yaml, Dictionary<string, int> Counts) GenerateOverrides(
        string modsRoot, Modlist modlist)
    {
        var yaml = new StringBuilder();
        yaml.AppendLine("# GENERATED by `mri-curation inspect` — do not edit by hand; re-run inspect");
        yaml.AppendLine("# after any change to the installed mods. Hand-written overrides.yaml is");
        yaml.AppendLine("# applied AFTER this file and wins on conflict.");
        yaml.AppendLine("version: 1");
        yaml.AppendLine("rules:");

        var counts = new Dictionary<string, int>();
        foreach (var mod in modlist.Mods)
        {
            var inspection = Inspect(modsRoot, mod);
            counts[inspection.Verdict] = counts.GetValueOrDefault(inspection.Verdict) + 1;

            switch (inspection.Verdict)
            {
                case "auto":
                case "core-picked":
                    yaml.AppendLine($"  - match: {{ slug: {Q(inspection.Slug)} }}");
                    yaml.AppendLine("    set:");
                    yaml.AppendLine($"      dataPaths: [{string.Join(", ", inspection.ChosenDataPaths.Select(Q))}]");
                    if (inspection.OtherCandidates.Count > 0)
                        yaml.AppendLine($"    # other candidates: {string.Join(" | ", inspection.OtherCandidates)}");
                    break;

                case "flagged":
                    yaml.AppendLine($"  # NEEDS CHOICE {Q(inspection.Slug)}: {string.Join(" | ", inspection.OtherCandidates)}");
                    break;

                case "no-data":
                    yaml.AppendLine($"  # NO DATA FOUND {Q(inspection.Slug)} — inspect {inspection.ExtractTo} manually");
                    break;
            }
        }

        return (yaml.ToString(), counts);
    }

    /// <summary>YAML double-quoted scalar (JSON-style escaping is valid YAML).</summary>
    private static string Q(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
