using System.Text;
using System.Text.Json;
using Mri.Core.Modlist;

namespace Mri.Curation.Inspect;

/// <summary>
/// Adopts modding-openmw.com's hand-curated per-mod choices for mods that
/// overlap their lists, matched by Nexus ID. Their curators already solved
/// variant selection (data_paths) and plugin activation (plugins) for
/// hundreds of the same mods; we translate their paths onto our directory
/// names and only keep choices whose directories actually exist on disk.
/// </summary>
public static class MomwAdopter
{
    public sealed record MomwEntry(
        string SourceList,
        string Dir,
        IReadOnlyList<string> DataPaths,
        IReadOnlyList<string> Plugins);

    /// <summary>Priority order: later lists never override earlier ones.</summary>
    public static readonly string[] DefaultLists =
    [
        "total-overhaul", "expanded-vanilla", "graphics-overhaul",
        "one-day-morrowind-modernization", "i-heart-vanilla-directors-cut", "i-heart-vanilla",
    ];

    public static async Task<Dictionary<string, MomwEntry>> FetchByNexusIdAsync(
        HttpClient http, string cacheDir, IEnumerable<string> lists, Action<string>? log = null)
    {
        Directory.CreateDirectory(cacheDir);
        var byNexusId = new Dictionary<string, MomwEntry>();

        foreach (var list in lists)
        {
            var cachePath = Path.Combine(cacheDir, $"{list}.json");
            string json;
            if (File.Exists(cachePath))
            {
                json = File.ReadAllText(cachePath);
            }
            else
            {
                json = await http.GetStringAsync($"https://modding-openmw.com/api/lists/{list}")
                    .ConfigureAwait(false);
                File.WriteAllText(cachePath, json);
            }

            using var doc = JsonDocument.Parse(json);
            var added = 0;
            foreach (var mod in doc.RootElement.EnumerateArray())
            {
                // The public API omits nexus_id; derive it from the url the
                // same way umo's NexusHandler does.
                var url = mod.TryGetProperty("url", out var u) ? u.GetString() ?? "" : "";
                var match = System.Text.RegularExpressions.Regex.Match(
                    url, @"https://www\.nexusmods\.com/.*?/mods/([0-9]+)");
                if (!match.Success)
                    continue;
                var nexusId = match.Groups[1].Value;
                if (byNexusId.ContainsKey(nexusId))
                    continue;

                var dir = mod.TryGetProperty("dir", out var d) ? d.GetString() ?? "" : "";
                var dataPaths = ReadStringArray(mod, "data_paths");
                var plugins = ReadStringArray(mod, "plugins");
                if (dir.Length == 0)
                    continue;

                byNexusId[nexusId] = new MomwEntry(list, dir, dataPaths, plugins);
                added++;
            }
            log?.Invoke($"  {list}: {added} new nexus-matched entries");
        }

        return byNexusId;
    }

    /// <summary>
    /// Their data_path "TheirDir/sub/dirs" → our "OurExtractTo/sub/dirs".
    /// Returns null when the path does not belong to their dir.
    /// </summary>
    public static string? TranslatePath(string momwPath, string momwDir, string ourExtractTo)
    {
        if (momwPath.Equals(momwDir, StringComparison.OrdinalIgnoreCase))
            return ourExtractTo;
        if (momwPath.StartsWith(momwDir + "/", StringComparison.OrdinalIgnoreCase))
            return ourExtractTo + momwPath[momwDir.Length..];
        return null;
    }

    public sealed record AdoptionResult(string Yaml, int AdoptedDataPaths, int ContentCandidates, int Skipped);

    public static AdoptionResult GenerateOverrides(
        string modsRoot,
        Modlist modlist,
        IReadOnlyDictionary<string, MomwEntry> momw)
    {
        var yaml = new StringBuilder();
        yaml.AppendLine("# GENERATED by `mri-curation adopt-momw` — data-path choices adopted from");
        yaml.AppendLine("# modding-openmw.com's hand-curated lists (matched by Nexus ID, translated");
        yaml.AppendLine("# to our directory names, kept only when the directories exist on disk).");
        yaml.AppendLine("# Layered AFTER layout.generated.yaml and BEFORE the hand overrides.");
        yaml.AppendLine("version: 1");
        yaml.AppendLine("rules:");

        int adopted = 0, contentCandidates = 0, skipped = 0;

        foreach (var mod in modlist.Mods)
        {
            if (mod.Source.NexusId is not { } nexusId ||
                !momw.TryGetValue(nexusId.ToString(), out var entry))
                continue;

            var extractTo = mod.Downloads.FirstOrDefault()?.ExtractTo ?? mod.Id;
            var categoryDir = ModlistCompiler.CategoryDir(mod.Category);

            var translated = entry.DataPaths
                .Select(p => TranslatePath(p, entry.Dir, extractTo))
                .ToList();

            if (translated.Count == 0 || translated.Any(t => t is null))
            {
                skipped++;
                continue;
            }

            // Disk truth gate: every adopted path must exist in OUR extraction.
            var missing = translated
                .Where(t => !Directory.Exists(Path.Combine(modsRoot, categoryDir, t!)))
                .ToList();
            if (missing.Count > 0)
            {
                skipped++;
                yaml.AppendLine($"  # NOT ADOPTED {Q(mod.Id)} (momw:{entry.SourceList}): " +
                                $"missing on disk: {string.Join(" | ", missing.Select(m => m!))}");
                continue;
            }

            if (!translated.SequenceEqual(mod.DataPaths, StringComparer.OrdinalIgnoreCase))
            {
                adopted++;
                yaml.AppendLine($"  - match: {{ slug: {Q(mod.Id)} }}   # momw:{entry.SourceList}");
                yaml.AppendLine("    set:");
                yaml.AppendLine($"      dataPaths: [{string.Join(", ", translated.Select(t => Q(t!)))}]");
            }

            if (entry.Plugins.Count > 0)
            {
                contentCandidates++;
                yaml.AppendLine($"  # content candidate {Q(mod.Id)} (momw:{entry.SourceList}): " +
                                string.Join(" | ", entry.Plugins));
            }
        }

        return new AdoptionResult(yaml.ToString(), adopted, contentCandidates, skipped);
    }

    private static IReadOnlyList<string> ReadStringArray(JsonElement element, string property)
    {
        if (!element.TryGetProperty(property, out var value) || value.ValueKind != JsonValueKind.Array)
            return Array.Empty<string>();
        return value.EnumerateArray()
            .Where(x => x.ValueKind == JsonValueKind.String)
            .Select(x => x.GetString()!)
            .ToList();
    }

    private static string Q(string s) =>
        "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
